version: "3.9"

services:
  api:
    build: .
    container_name: ms-productos
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - DB_NAME=ecommerce_db

  db:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
